# Docker Compose override for integration testing
# Usage: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build
# This configuration removes persistence for clean test runs

services:
  postgres:
    # Complete override for testing - no persistent volumes, only tmpfs
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=512m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles
      # Speed up PostgreSQL for testing
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    command: >
      postgres
      -c shared_preload_libraries=vector
      -c log_statement=none
      -c log_min_duration_statement=-1
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_buffers=16MB
      -c checkpoint_completion_target=0.9
    
  embedding-service:
    # Optional: reduce resource usage for testing
    environment:
      - PORT=8001
      - DEBUG=false
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/articles
    
  articles-api:
    # Optional: increase log level for debugging tests
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=articles
      - DB_SSLMODE=disable
      - JWT_SECRET=test-jwt-secret-key
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - LOG_LEVEL=debug

# Remove the persistent volume completely for test runs
volumes: {}